baseURL = "http://lilsoak.com/"
languageCode = "en-us"
title = "Lil'Soak Designs"
theme = "ananke"

[params]
  favicon = ""
  description = "Sewing hope through handmade goods"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Emma-in-pink-shirt-and-Gladie-in-yellow-shirt-web.jpg"
  recent_posts_number = 2